const STORAGE_KEY='pfm-agentic-astra-v1';
const seedAgents=[
{id:'signal',name:'Signal Intelligence',domain:'Strategy',mandate:'Sense global, regional and local government signals and translate them into evidence-backed fiscal implications.',status:'running',autonomy:'observe',approvalThreshold:0,color:'#55d7ff',lastAction:'Processed 18 new macro and policy signals',confidence:94,enabled:true,subagents:[{name:'Global Signals',mandate:'Macro, geopolitical and commodity sensing'},{name:'Regional Signals',mandate:'GCC and regional economic sensing'},{name:'Local Direction',mandate:'Government direction and mandate sensing'}]},
{id:'strategy',name:'Strategic Fiscal Intelligence',domain:'Strategy',mandate:'Formulate strategic fiscal directions, priorities, scenarios and implications from approved evidence.',status:'idle',autonomy:'recommend',approvalThreshold:0,color:'#9d7cff',lastAction:'Updated downside fiscal scenario',confidence:91,enabled:true,subagents:[{name:'Scenario Analyst',mandate:'Baseline, upside and downside scenarios'}]},
{id:'allocation',name:'Budget Allocation',domain:'Budget',mandate:'Recommend entity and programme allocations within approved fiscal envelopes using mandates, demand, performance and obligations.',status:'waiting_approval',autonomy:'prepare_action',approvalThreshold:1000000,color:'#45f0d0',lastAction:'Prepared allocation package for 4 entities',confidence:89,enabled:true,subagents:[{name:'Baseline Builder',mandate:'Build expenditure baselines'},{name:'Allocation Optimizer',mandate:'Optimize allocations subject to fiscal envelope'}]},
{id:'challenge',name:'Budget Challenge',domain:'Budget',mandate:'Independently challenge budget requests, assumptions, duplicates, unit costs, delivery readiness and under-spend patterns.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#ffcf6e',lastAction:'Flagged AED 42M unsupported growth',confidence:96,enabled:true,subagents:[]},
{id:'execution',name:'Budget Execution',domain:'Budget',mandate:'Monitor approved and adjusted budget, commitments, obligations, actuals, accruals and forecast outturn.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#55d7ff',lastAction:'Reforecast year-end utilization to 94.1%',confidence:95,enabled:true,subagents:[{name:'Virement Analyst',mandate:'Assess budget amendments and transfers'},{name:'Delay Detector',mandate:'Detect execution and procurement delays'}]},
{id:'cash',name:'Cash Forecasting',domain:'Treasury',mandate:'Forecast government and entity cash needs across daily, monthly and rolling horizons.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#45f0d0',lastAction:'Updated 90-day liquidity forecast',confidence:93,enabled:true,subagents:[{name:'Entity Needs',mandate:'Forecast entity monthly funding needs'}]},
{id:'funding',name:'Funding & Transfers',domain:'Treasury',mandate:'Prepare governed funding and transfer instructions after budget, liquidity and authority validation.',status:'waiting_approval',autonomy:'prepare_action',approvalThreshold:500000,color:'#9d7cff',lastAction:'Prepared AED 86M monthly funding batch',confidence:98,enabled:true,subagents:[]},
{id:'liquidity',name:'Treasury & Liquidity',domain:'Treasury',mandate:'Maintain liquidity intelligence, banking exposure, surplus placement options and maturity profile.',status:'idle',autonomy:'recommend',approvalThreshold:0,color:'#55d7ff',lastAction:'Reviewed deposit maturity ladder',confidence:92,enabled:true,subagents:[{name:'Bank Exposure',mandate:'Monitor counterparty and concentration limits'},{name:'Surplus Placement',mandate:'Recommend maturity-matched surplus deposits'}]},
{id:'revenue',name:'Revenue Intelligence',domain:'Revenue',mandate:'Monitor revenue forecasts, assessments, collections, deposits, exemptions, refunds and anomalies.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#45f0d0',lastAction:'Detected collection variance in 2 streams',confidence:94,enabled:true,subagents:[{name:'Pricing Intelligence',mandate:'Analyze regulated government pricing and fiscal impact'},{name:'Revenue Legal',mandate:'Retrieve authoritative legal basis and exceptions'}]},
{id:'recon',name:'Revenue Reconciliation',domain:'Revenue',mandate:'Reconcile source systems, gateways, banks and general ledger; classify exceptions and prepare corrections.',status:'exception',autonomy:'execute_low_risk',approvalThreshold:100000,color:'#ff738d',lastAction:'11 unmatched settlements require review',confidence:99,enabled:true,subagents:[{name:'Refund Validator',mandate:'Validate refund eligibility and source transaction'}]},
{id:'accounting',name:'Accounting Operations',domain:'Accounting',mandate:'Monitor accounting integrity, classifications, journals, clearing accounts, accruals, receivables and payables.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#55d7ff',lastAction:'Classified 23 accounting exceptions',confidence:97,enabled:true,subagents:[{name:'Monthly Close',mandate:'Orchestrate close readiness and outstanding controls'},{name:'Intergovernmental',mandate:'Match inter-entity receivables and payables'}]},
{id:'consolidation',name:'Government Consolidation',domain:'Accounting',mandate:'Validate entity submissions, accounting mappings, inter-entity eliminations and government-wide consolidation.',status:'idle',autonomy:'prepare_action',approvalThreshold:0,color:'#9d7cff',lastAction:'Prepared consolidation readiness pack',confidence:95,enabled:true,subagents:[{name:'Elimination',mandate:'Prepare inter-entity elimination entries'},{name:'Statements',mandate:'Prepare draft consolidated statements and disclosures'}]},
{id:'health',name:'Fiscal Health',domain:'Intelligence',mandate:'Consolidate budget, cash, accrual, revenue, risk and operational integrity into near-real-time fiscal health intelligence.',status:'running',autonomy:'recommend',approvalThreshold:0,color:'#45f0d0',lastAction:'Fiscal Health Index updated to 82',confidence:92,enabled:true,subagents:[{name:'Cash–Accrual Bridge',mandate:'Reconcile budget, cash and accrual positions'},{name:'Risk Monitor',mandate:'Detect emerging fiscal and operational risk'}]},
{id:'assurance',name:'PFM Assurance',domain:'Assurance',mandate:'Independently test evidence, authority, segregation of duties, policy compliance and agent decision quality.',status:'running',autonomy:'observe',approvalThreshold:0,color:'#ffcf6e',lastAction:'Validated 37 agent handoffs',confidence:99,enabled:true,subagents:[]}
];
const seedActivities=[
{agent:'Revenue Reconciliation',action:'Classified 11 unmatched bank settlements',detail:'AED 3.8M · exception queue',time:'now',status:'exception'},
{agent:'Budget Execution',action:'Reforecast Entity B capital utilization',detail:'91.2% → 86.7% due to milestone delay',time:'2m',status:'running'},
{agent:'Signal Intelligence',action:'Added regional interest-rate signal',detail:'Evidence confidence 96% · treasury exposure mapped',time:'5m',status:'running'},
{agent:'Funding & Transfers',action:'Funding batch waiting for approval',detail:'AED 86M · 4 entities · authority gate G3',time:'8m',status:'waiting_approval'},
{agent:'Accounting Operations',action:'Monthly close readiness recalculated',detail:'87% · 17 open controls',time:'12m',status:'running'}
];
let state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{agents:seedAgents,activities:seedActivities};
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#page-title').textContent={command:'Command Center',agents:'Agents',reports:'Reports',config:'Configuration'}[id];}
$$('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));$$('[data-view-target]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewTarget));
function renderActivities(){const box=$('#activity-stream');box.innerHTML=state.activities.slice(0,8).map(a=>`<div class="activity"><span class="activity-dot" style="background:${a.status==='exception'?'var(--danger)':a.status==='waiting_approval'?'var(--amber)':'var(--cyan)'}"></span><div><p><strong>${a.agent}</strong> · ${a.action}</p><small>${a.detail}</small></div><time>${a.time}</time></div>`).join('');}
function renderCycle(){const nodes=['Signals','Strategy','Fiscal Plan','Budget','Execution','Treasury','Revenue','Accounting','Consolidation','Fiscal Health'];$('#cycle-flow').innerHTML=nodes.map((n,i)=>`<span class="cycle-node">${n}</span>${i<nodes.length-1?'<span class="cycle-arrow">→</span>':''}`).join('');}
function renderExceptions(){const rows=[['Revenue reconciliation','11 unmatched settlements','high'],['Capital execution','AED 210M forecast slippage','medium'],['Monthly close','3 bank reconciliations pending','medium'],['Funding request','AED 86M awaiting authority approval','medium']];$('#exceptions').innerHTML=rows.map(r=>`<div class="exception"><div><p>${r[0]}</p><small>${r[1]}</small></div><span class="severity ${r[2]}">${r[2].toUpperCase()}</span></div>`).join('');}
function renderAgents(){const domain=$('#agent-domain-filter').value,status=$('#agent-status-filter').value;const list=state.agents.filter(a=>(domain==='all'||a.domain===domain)&&(status==='all'||a.status===status));$('#agent-grid').innerHTML=list.map(a=>`<article class="agent-card" data-agent="${a.id}" style="--agent-color:${a.color}"><div class="agent-top"><div class="agent-orb"></div><span class="agent-status ${a.status}">${a.status.replace('_',' ')}</span></div><h3>${a.name}</h3><span class="agent-domain">${a.domain} · ${a.autonomy}</span><p>${a.mandate}</p><div class="agent-meta"><span>${a.subagents.length} sub-agents</span><span>${a.confidence}% confidence</span></div></article>`).join('');$$('.agent-card').forEach(c=>c.onclick=()=>openAgent(c.dataset.agent));}
function initFilters(){const domains=[...new Set(state.agents.map(a=>a.domain))];$('#agent-domain-filter').innerHTML='<option value="all">All domains</option>'+domains.map(d=>`<option>${d}</option>`).join('');$('#agent-domain-filter').onchange=renderAgents;$('#agent-status-filter').onchange=renderAgents;}
function openAgent(id){const a=state.agents.find(x=>x.id===id);const related=state.activities.filter(x=>x.agent===a.name);$('#dialog-content').innerHTML=`<p>${a.mandate}</p><div class="detail-grid"><div class="detail-box"><span>STATUS</span><strong>${a.status}</strong></div><div class="detail-box"><span>AUTOMATION</span><strong>${a.autonomy}</strong></div><div class="detail-box"><span>CONFIDENCE</span><strong>${a.confidence}%</strong></div><div class="detail-box"><span>APPROVAL THRESHOLD</span><strong>AED ${Number(a.approvalThreshold).toLocaleString()}</strong></div></div><h3>Current / last action</h3><div class="detail-box"><strong>${a.lastAction}</strong></div><h3>Sub-agents</h3>${a.subagents.length?a.subagents.map(s=>`<div class="subagent"><strong>${s.name}</strong><small>${s.mandate}</small></div>`).join(''):'<p class="agent-domain">No sub-agents configured.</p>'}<div class="timeline"><h3>Activity trail</h3>${related.length?related.map(x=>`<div class="timeline-item"><strong>${x.action}</strong><br><small>${x.detail} · ${x.time}</small></div>`).join(''):'<div class="timeline-item"><small>No recent event in current demo window.</small></div>'}</div>`;$('#agent-dialog').showModal();}
function loadConfigOptions(){const sel=$('#config-agent');sel.innerHTML=state.agents.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');sel.onchange=loadConfig;loadConfig();}
function loadConfig(){const a=state.agents.find(x=>x.id===$('#config-agent').value)||state.agents[0];$('#config-name').value=a.name;$('#config-mandate').value=a.mandate;$('#config-autonomy').value=a.autonomy;$('#config-threshold').value=a.approvalThreshold;$('#config-enabled').checked=a.enabled;$('#subagent-list').innerHTML=a.subagents.map((s,i)=>`<div class="subagent"><strong>${s.name}</strong><small>${s.mandate}</small><button class="link-btn remove-sub" data-i="${i}">Remove</button></div>`).join('')||'<div class="empty-state" style="height:100px">No sub-agents configured.</div>';$$('.remove-sub').forEach(b=>b.onclick=()=>{a.subagents.splice(+b.dataset.i,1);save();loadConfig();renderAgents();});}
$('#save-config-btn').onclick=()=>{const a=state.agents.find(x=>x.id===$('#config-agent').value);Object.assign(a,{name:$('#config-name').value,mandate:$('#config-mandate').value,autonomy:$('#config-autonomy').value,approvalThreshold:+$('#config-threshold').value,enabled:$('#config-enabled').checked});state.activities.unshift({agent:a.name,action:'Configuration updated',detail:`Autonomy: ${a.autonomy} · threshold AED ${a.approvalThreshold.toLocaleString()}`,time:'now',status:'running'});save();renderAll();};
$('#add-subagent-btn').onclick=()=>{const a=state.agents.find(x=>x.id===$('#config-agent').value);const name=prompt('Sub-agent name');if(!name)return;const mandate=prompt('Sub-agent mandate');if(!mandate)return;a.subagents.push({name,mandate});save();loadConfig();renderAgents();};
$('#new-agent-btn').onclick=()=>$('#new-agent-dialog').showModal();$('#new-agent-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const name=f.get('name');state.agents.push({id:'custom-'+Date.now(),name,domain:f.get('domain'),mandate:f.get('mandate'),status:'idle',autonomy:f.get('autonomy'),approvalThreshold:0,color:'#55d7ff',lastAction:'Created and awaiting first run',confidence:0,enabled:true,subagents:[]});state.activities.unshift({agent:name,action:'Agent created',detail:'Custom agent added to registry',time:'now',status:'running'});save();$('#new-agent-dialog').close();e.target.reset();initFilters();loadConfigOptions();renderAll();});
$('#pulse-btn').onclick=()=>{const score=80+Math.floor(Math.random()*7);$('#health-score').textContent=score;const candidates=state.agents.filter(a=>a.enabled);const a=candidates[Math.floor(Math.random()*candidates.length)];a.status='running';a.lastAction='Fiscal pulse validation completed';state.activities.unshift({agent:a.name,action:'Fiscal pulse completed',detail:`Health index ${score} · evidence and exception checks refreshed`,time:'now',status:'running'});save();renderActivities();renderAgents();};
$('#generate-report-btn').onclick=()=>{const type=$('#report-type').value,entity=$('#report-entity').value,mandate=$('#report-mandate').value,period=$('#report-period').value;const rows=[['Entity A','18.2B','12.1B','10.4B','93.8%'],['Entity B','14.7B','9.8B','8.1B','86.7%'],['Entity C','11.3B','7.5B','6.9B','95.1%'],['Other entities','34.2B','22.3B','18.2B','94.6%']];$('#report-output').innerHTML=`<div class="report-header"><div><p class="eyebrow">GENERATED FISCAL REPORT</p><h2>${type}</h2><small>${entity} · ${mandate} · ${period}</small></div><div><span class="live-chip">EVIDENCE-LINKED DRAFT</span></div></div><div class="report-kpis"><div class="report-kpi"><span>APPROVED</span><strong>AED 78.4B</strong></div><div class="report-kpi"><span>COMMITTED</span><strong>AED 51.7B</strong></div><div class="report-kpi"><span>PAID</span><strong>AED 43.6B</strong></div><div class="report-kpi"><span>FORECAST OUTTURN</span><strong>94.1%</strong></div></div><table class="report-table"><thead><tr><th>Entity</th><th>Budget</th><th>Committed</th><th>Paid</th><th>Forecast</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table><p style="font-size:11px;color:var(--muted);margin-top:18px">Flags: ${$('#include-delays').checked?'capital delivery delay in Entity B; ':''}${$('#include-exceptions').checked?'11 reconciliation exceptions; ':''}${$('#include-forecast').checked?'year-end forecast included; ':''}${$('#include-evidence').checked?'evidence references enabled.':''}</p>`;state.activities.unshift({agent:'Fiscal Health',action:`Generated ${type} report`,detail:`${entity} · ${period}`,time:'now',status:'running'});save();renderActivities();};
function renderAll(){renderActivities();renderCycle();renderExceptions();renderAgents();loadConfig();}
initFilters();loadConfigOptions();renderAll();
