CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`slug` text NOT NULL,
	`category` text NOT NULL,
	`owner` text DEFAULT 'Unassigned' NOT NULL,
	`stage` text DEFAULT 'Discover' NOT NULL,
	`maturity` text DEFAULT 'concept' NOT NULL,
	`data_policy` text DEFAULT 'synthetic-only' NOT NULL,
	`production_ready` integer DEFAULT false NOT NULL,
	`risk_level` text DEFAULT 'Not assessed' NOT NULL,
	`gate_progress` integer DEFAULT 0 NOT NULL,
	`technical_status` text DEFAULT 'Not validated' NOT NULL,
	`pilot_wave` integer DEFAULT 4 NOT NULL,
	`source_url` text DEFAULT '' NOT NULL,
	`document_key` text,
	`document_name` text,
	`document_type` text,
	`financial_kpi` real,
	`operational_kpi` real,
	`customer_kpi` real,
	`quality_kpi` real,
	`innovation_kpi` real,
	`kpi_period` text,
	`notes` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
