import { agents, priorities, siteConfig, solutions } from "./site-config";
const Arrow=()=> <span aria-hidden="true">→</span>;
const domains=["Strategy & Execution","Governance","Performance","Processes","Services","Organization & People","Data & Digital","AI Readiness"];
export default function Home(){return <main>
<header className="site-header"><a className="wordmark" href="#top"><strong>TRANSFORMATION</strong><span>INTELLIGENCE</span></a><nav>{siteConfig.navigation.map(x=><a key={x.label} href={x.href}>{x.label}</a>)}</nav><a className="button small" href="#assessment">Start Assessment</a></header>
<section className="hero" id="top"><div><p className="kicker">TRANSFORMATION INTELLIGENCE</p><h1>Transform Your Organization. <em>Powered by Intelligence.</em></h1><p className="lede">Connect strategy, performance, processes, services, governance and AI to understand how your organization operates, identify what needs to improve, and turn insight into measurable action.</p><div className="actions"><a className="button" href="#assessment">Assess Your Organization <Arrow/></a><a className="button ghost" href="#platform">Explore the Platform</a></div><a className="text-link" href="#contact">Talk to a Transformation Expert <Arrow/></a></div><div className="map"><div className="core">Executive<br/>Intelligence</div>{["Strategy","Performance","Processes","Services","Governance","AI"].map((x,i)=><span key={x} className={"node n"+i}>{x}</span>)}</div></section>
<section className="proof">{["Strategy","Operational Excellence","Services","Performance","Governance & Risk","Enterprise AI"].map(x=><span key={x}>{x}</span>)}</section>
<section className="section"><Heading kicker="START WITH THE PRIORITY" title="What would you like to improve?" text="Choose the organizational challenge that matters most. Each priority connects to a solution, assessment and transformation path."/><div className="grid four">{priorities.map(([t,d],i)=><Card key={t} number={i+1} title={t} text={d}/>)}</div></section>
<section className="dark split"><div><p className="kicker light">THE ORGANIZATIONAL PROBLEM</p><h2>Organizations have data. The challenge is connecting it.</h2></div><p>Strategies, KPIs, processes, services, risks, controls, systems and organizational information often sit in separate tools and management cycles. Transformation Intelligence creates a connected view of performance, constraints and opportunities.</p></section>
<section className="section" id="platform"><Heading kicker="TRANSFORMATION INTELLIGENCE PLATFORM" title="One intelligence layer across your organization." text="Create a connected view of organizational performance and use specialized AI capabilities to analyze evidence, identify gaps and support management decisions."/><div className="stack"><b>Executive Intelligence</b><i>↓</i><strong>AI Orchestration</strong><i>↓</i><div>{["Strategy","Process","Service","Performance","Governance"].map(x=><span key={x}>{x} Agent</span>)}</div><i>↓</i><div className="knowledge">{["Strategy","Objectives","KPIs","Initiatives","Organization","Services","Processes","People","Systems","Data","Risks","Controls","Policies","Evidence"].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="section tinted"><Heading kicker="SOLUTIONS" title="Transform every layer of your organization."/><div className="grid four">{solutions.map(([t,d])=><Card key={t} title={t} text={d}/>)}</div></section>
<section className="dark section-wide"><Heading kicker="GOVERNED AI" title="Specialized intelligence for complex transformation." text="AI agents support specific management disciplines rather than operating as an uncontrolled general-purpose chatbot."/><div className="grid four">{agents.map(([t,d])=><Card key={t} title={t} text={d} dark/>)}</div></section>
<section className="section" id="assessment"><div className="assessment"><div><p className="kicker">TRANSFORMATION READINESS ASSESSMENT</p><h2>How ready is your organization for transformation?</h2><p>Establish an initial view of organizational maturity, gaps and improvement priorities across eight management domains.</p><div className="pills">{domains.map(x=><span key={x}>{x}</span>)}</div><a className="button" href="#contact">Start Assessment <Arrow/></a></div><div className="score"><small>ILLUSTRATIVE MATURITY PROFILE</small><strong>67<em>/100</em></strong>{[["Strategy",78],["Performance",69],["Processes",61],["Services",73],["Governance",65],["AI Readiness",54]].map(([x,v])=><div className="bar" key={String(x)}><span>{x}</span><i><b style={{width:v+"%"}}/></i><em>{v}</em></div>)}</div></div></section>
<section className="section"><Heading kicker="INDUSTRIES" title="Designed for complex and regulated environments."/><div className="grid four">{[["Government & Public Sector","Institutional performance, government services, operational excellence, governance and digital transformation."],["Financial Services","Transformation, operational performance, governance, controls and responsible AI."],["Healthcare","Service management, operations, workforce and performance improvement."],["Large & Regulated Enterprises","Operating models, governance, enterprise architecture, performance and intelligent automation."]].map(([t,d])=><Card key={t} title={t} text={d}/>)}</div></section>
<section className="trust"><Heading kicker="RESPONSIBLE INTELLIGENCE" title="Enterprise intelligence requires enterprise governance."/><div className="grid four">{[["Human Oversight","Defined authority remains responsible for material decisions."],["Evidence & Traceability","Findings and recommendations connect to supporting evidence."],["Access Control","Information and functionality are governed by user roles."],["Auditability","Analysis, recommendations, reviews and approvals retain history."]].map(([t,d])=><Card key={t} title={t} text={d} dark/>)}</div></section>
<section className="section final" id="contact"><p className="kicker">START THE CONVERSATION</p><h2>Where should your transformation start?</h2><p>Assess your organization, identify priority opportunities and establish an evidence-based path to measurable improvement.</p><div className="actions"><a className="button" href="mailto:contact@example.com">Talk to an Expert <Arrow/></a><a className="button ghost" href="#platform">Explore Platform</a></div><small>Development placeholder contact address — replace before production.</small></section>
<footer><strong>TRANSFORMATION INTELLIGENCE</strong><p>Enterprise transformation powered by management expertise, organizational intelligence and governed AI.</p><div>© 2026 {"{{LEGAL_NAME}}"}. All rights reserved.</div></footer>
</main>}
function Heading({kicker,title,text}:{kicker:string,title:string,text?:string}){return <div className="heading"><p className="kicker">{kicker}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Card({number,title,text,dark=false}:{number?:number,title:string,text:string,dark?:boolean}){return <article className={"card "+(dark?"card-dark":"")}>{number&&<small>{String(number).padStart(2,"0")}</small>}<h3>{title}</h3><p>{text}</p></article>}
