"use client";
import {useEffect,useMemo,useState} from "react";
type Eng={id:string;organization:string;objective:string;priorities:string[];assessment?:{overall:number;level:string}};
type Finding={finding_id:string;agent:string;domain:string;title:string;statement:string;evidence_ids:string[];severity:string;confidence:number;status:string;recommendation:string};
type Case={status:string;findings:Finding[];synthesis?:Finding;normalized_counts?:Record<string,number>;evidence_quality?:{ready:boolean}};
const agents=[["Processes","Process Intelligence Agent"],["Performance","Performance Intelligence Agent"],["Governance","Governance, Risk & Control Agent"]];
export function WorkspaceClient(){
 const [eng,setEng]=useState<Eng|null>(null),[data,setData]=useState<Case|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{try{const e=JSON.parse(localStorage.getItem("ti-diagnostic-engagement")||"null");setEng(e);if(e)refresh(e.id)}catch{}},[]);
 async function refresh(id=eng?.id){if(!id)return;const r=await fetch("/api/diagnostics/"+id,{cache:"no-store"});if(r.ok)setData(await r.json())}
 async function ensure(){if(!eng)return false;const r=await fetch("/api/diagnostics/"+eng.id,{cache:"no-store"});if(r.ok)return true;const c=await fetch("/api/diagnostics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(eng)});return c.ok}
 async function upload(files:FileList|null){if(!eng||!files)return;setBusy(true);setMsg("");try{await ensure();for(const file of Array.from(files)){const fd=new FormData();fd.append("file",file);fd.append("classification","Internal");const r=await fetch("/api/diagnostics/"+eng.id+"/evidence",{method:"POST",body:fd});if(!r.ok)throw new Error(await r.text())}setMsg("Evidence stored and extracted.");await refresh()}catch(e){setMsg(String(e))}finally{setBusy(false)}}
 async function execute(){if(!eng)return;setBusy(true);try{await ensure();const domains=(eng.priorities||[]).filter(x=>["Processes","Performance","Governance"].includes(x));const r=await fetch("/api/diagnostics/"+eng.id+"/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({domains:domains.length?domains:["Processes","Performance","Governance"]})});if(!r.ok)throw new Error(await r.text());setData(await r.json());setMsg("Deterministic diagnostic execution completed. Review findings below.")}catch(e){setMsg(String(e))}finally{setBusy(false)}}
 async function decide(f:Finding,decision:string){if(!eng)return;const reason=prompt("Decision reason / reviewer note:");if(!reason)return;let modified_statement:string|undefined;if(decision==="modified"){modified_statement=prompt("Approved replacement statement:",f.statement)||undefined;if(!modified_statement)return}const r=await fetch("/api/diagnostics/"+eng.id+"/findings/"+f.finding_id+"/decision",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,reviewer_role:"DIAGNOSTIC_REVIEWER",reason,modified_statement})});if(r.ok){setData(await r.json());setMsg("Human decision recorded.")}else setMsg(await r.text())}
 const assigned=useMemo(()=>agents.filter(a=>!eng?.priorities?.length||eng.priorities.includes(a[0])),[eng]);
 if(!eng)return <div className="empty-state"><h2>No diagnostic engagement found.</h2><a className="button" href="/diagnostic/start">Create engagement</a></div>;
 return <div className="diagnostic-shell"><div className="workspace-banner"><div><p className="kicker">CLIENT WORKSPACE · {eng.id}</p><h2>{eng.organization}</h2><p>{eng.objective}</p></div><div className="mini-score"><strong>{eng.assessment?.overall??"—"}</strong><span>{eng.assessment?.level||"Baseline"}</span></div></div>
 <div className="journey"><b>Assessment ✓</b><b>Scope ✓</b><b className={!data?"active":""}>Evidence</b><b className={data?.status==="human_review"?"active":""}>Analysis</b><b>Human Review</b><b>Report</b></div>
 <section className="workspace-grid"><article className="workspace-card"><p className="kicker">REAL EVIDENCE CENTER</p><h3>Store and extract evidence</h3><p>Files are sent to the diagnostic backend, hashed, stored and extracted. Structured records are normalized before deterministic analysis.</p><input className="file-input" disabled={busy} type="file" multiple accept=".pdf,.docx,.xlsx,.csv,.json,.txt,.md,.pptx" onChange={e=>upload(e.target.files)}/>{data?.normalized_counts&&<p>Normalized: {Object.entries(data.normalized_counts).map(([k,v])=>k+" "+v).join(" · ")}</p>}</article>
 <article className="workspace-card"><p className="kicker">CONTROLLED EXECUTION</p><h3>Run evidence and specialist engines</h3><p>Evidence Quality executes first. Canonical records are then routed into P10 Process Intelligence, P09 Performance Review and the deterministic enterprise GRC review.</p><div className="priority-list">{assigned.map(a=><span key={a[0]}>{a[1]}</span>)}</div><button className="button" disabled={busy} onClick={execute}>{busy?"Working…":"Execute diagnostic →"}</button></article></section>
 {msg&&<section className="workspace-card"><strong>{msg}</strong></section>}
 {data?.findings?.length?<section className="section-in-workspace"><p className="kicker">STRUCTURED FINDINGS · HUMAN AUTHORITY GATE</p><h2>Review every conclusion before publication</h2><div className="evidence-list">{data.findings.map(f=><article className="workspace-card" key={f.finding_id}><small>{f.agent} · {f.domain} · {f.severity} · confidence {Math.round(f.confidence*100)}%</small><h3>{f.title}</h3><p>{f.statement}</p><p><b>Evidence:</b> {f.evidence_ids.join(", ")||"None"}</p><p><b>Recommendation:</b> {f.recommendation}</p><p><b>Status:</b> {f.status}</p><div className="priority-list"><button onClick={()=>decide(f,"approved")}>Approve</button><button onClick={()=>decide(f,"modified")}>Modify</button><button onClick={()=>decide(f,"rejected")}>Reject</button><button onClick={()=>decide(f,"returned")}>Request more evidence</button></div></article>)}</div></section>:null}
 {data?.synthesis&&<section className="workspace-card review-gate"><p className="kicker">EXECUTIVE SYNTHESIS</p><h3>{data.synthesis.title}</h3><p>{data.synthesis.statement}</p><p>{data.synthesis.recommendation}</p><a className="button" href={"/api/diagnostics/"+eng.id+"/report"} target="_blank">Open controlled report →</a></section>}
 </div>
}